// <auto-generated />
namespace TrabalhoPraticoPWeb1718.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addInstituicaoAutorizacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addInstituicaoAutorizacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201712232224525_addInstituicaoAutorizacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
